### ISSUE TITLE
Exercise 9 - referenced function is not existing

### ISSUE THREAD

**Issue by tpfau** [wmvanvliet/gizmo#40]
Exercise 9 refers to a `multiplication_table` function, but that function does not exist. 
I now documented the fibonacci code.

**Comment by wmvanvliet** [comment]
Good catch!

**Comment by wmvanvliet** [comment]
Fixed in https://github.com/wmvanvliet/gizmo/commit/62b70a0598d6319d0ae018d5d01040c8b465096a
